[package]
name    = "rolldown_common"
version = "0.0.1"

homepage.workspace   = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
rolldown_oxc       = { path = "../rolldown_oxc" }
rolldown_sourcemap = { path = "../rolldown_sourcemap" }
oxc                = { workspace = true, features = ["semantic"] }
rustc-hash         = { workspace = true }
index_vec          = { workspace = true }
sugar_path         = { workspace = true }
regex              = { workspace = true }
once_cell          = { workspace = true }
string_wizard      = { workspace = true }
