[package]
name                 = "rolldown_rstr"
version              = "0.0.1"
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc = { workspace = true }


[lints]
workspace = true
