name: Release

on:
  # Manually released
  workflow_dispatch:
  # Every day at midnight (nightly)
  schedule:
    - cron: '0 0 * * *'
  # Uncomment to test in PRs (its safe)
  # pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    name: Plan release
    runs-on: ubuntu-latest
    outputs:
      # publish: ${{ github.event_name == 'workflow_dispatch' }}
      nightly: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    steps:
      - run: 'echo "Planning release"'

  build:
    name: Build bindings and node packages
    uses: ./.github/workflows/reusable-release-build.yml

  test:
    needs:
      - plan
      - build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

          - os: macos-14
            target: aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    name: Test ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Pull submodules for additional files

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download Node Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/rolldown/dist
          name: node-artifact

      - name: Download Binding Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/rolldown/src
          name: bindings-${{ matrix.target }}

      - name: Download Binding Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/rolldown/dist/shared
          name: bindings-${{ matrix.target }}

      - name: List rolldown dist
        run: ls -R ./packages/rolldown
        shell: bash

      - name: Node Test
        run: pnpm test

  publish:
    name: Publish npm Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write # for softprops/action-gh-release@v1
      id-token: write # for `npm publish --provenance`
    needs:
      - plan
      - build
      # - test
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install && git reset --hard # fix pnpm install add new line for package.json

      - name: Download Binding Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/rolldown/artifacts

      - name: List rolldown package
        run: ls -R ./packages/rolldown
        shell: bash

      - name: Move Binding Artifacts
        run: pnpm --filter rolldown artifacts

      - name: List rolldown package
        run: ls -R ./packages/rolldown/npm
        shell: bash

      - name: Download Node Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/rolldown/dist
          name: node-artifact

      - name: Prepare publish
        run: |
          find ./packages/ -type d -maxdepth 1 -exec cp LICENSE {} \;
          find ./packages/ -type d -maxdepth 1 -exec cp THIRD-PARTY-LICENSE {} \;
          git config --global user.email "github-actions[bot]@users.noreply.github.com";
          git config --global user.name "github-actions[bot]";

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.ROLLDOWN_NPM_TOKEN }}

      # Only runs when manually dispatched
      - name: Publish
        if: ${{ needs.plan.outputs.publish == 'true' }}
        run: |
          pnpm changeset version
          git add --all
          git commit -m "chore: Release"
          pnpm changeset publish
          git push --follow-tags
        env:
          NPM_TOKEN: ${{ secrets.ROLLDOWN_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only runs for nightly
      - name: Publish nightly
        if: ${{ needs.plan.outputs.nightly == 'true' }}
        run: |
          node ./scripts/bump-version.js canary
          pnpm publish -r --tag nightly --dry-run --no-git-checks
          pnpm publish -r --tag nightly --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.ROLLDOWN_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
